services:
  ddb:
    image: amazon/dynamodb-local
    ports:
      - "7654:8000"
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"


  ddb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://ddb:8000" # service_name:container_port
      # AWS_REGION: dummy
      # AWS_ACCESS_KEY_ID: abc
      # AWS_SECRET_ACCESS_KEY: def
    depends_on:
      - ddb
