services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      DDB_ENDPOINT_URL: http://ddb:8000
    depends_on:
      - ddb

  ddb:
    image: amazon/dynamodb-local
    ports:
      - "7654:8000"
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"

  ddb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://ddb:8000" # service_name:container_port
    depends_on:
      - ddb
