services:
  ddb:
    image: amazon/dynamodb-local
    ports:
      - "7654:8000"
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    networks:
      - url-shortener-net

  ddb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://ddb:8000" # service_name:container_port
    depends_on:
      - ddb
    networks:
      - url-shortener-net

volumes:
  dynamodb_data:

networks:
  url-shortener-net:
    name: url-shortener-network
