FROM python:3.11-slim-bookworm

# Makefile commands
RUN apt-get update && apt-get install make

ENV POETRY_VERSION=1.8.3
ENV POETRY_VIRTUALENVS_CREATE=false
ENV POETRY_VIRTUALENVS_IN_PROJECT=false
ENV PIP_ROOT_USER_ACTION=ignore

RUN pip install --upgrade pip
RUN pip install poetry==${POETRY_VERSION}

COPY pyproject.toml poetry.lock .

WORKDIR /app

RUN poetry install --with dev

CMD ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "8080"]
