name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'frontend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build
    - name: lint
      run: make lint

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build
    - name: test
      run: make testwithcoverage

  deploy:
    needs: [lint, test]
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'peacefulseeker'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: deploy
      uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
